name: Multi-Cloud Docker Push

on:
  push:
    branches:
      -master

env:
  IMAGE_NAME: app
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-south1
  GCP_REPO: my-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME .

    # =========================
    # AWS ECR (Access Key + Secret)
    # =========================
    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region $AWS_REGION

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Push to ECR
      run: |
        docker tag $IMAGE_NAME:latest \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest

        docker push \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest

    # =========================
    # GCP (Workload Identity Federation)
    # =========================
    - name: Authenticate to GCP (WIF)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev

    - name: Push to GCP Artifact Registry
      run: |
        docker tag $IMAGE_NAME:latest \
        $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPO/$IMAGE_NAME:latest

        docker push \
        $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPO/$IMAGE_NAME:latest